package migu

type SearchSongResponse struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
	Data struct {
		BestShow struct {
			BestShowSinger struct {
				Id           string      `json:"id"`
				Name         string      `json:"name"`
				SmallPic     string      `json:"smallPic"`
				MediumPic    string      `json:"mediumPic"`
				LargePic     string      `json:"largePic"`
				SongNum      int         `json:"songNum"`
				AlbumNum     int         `json:"albumNum"`
				MvNum        int         `json:"mvNum"`
				HighlightStr interface{} `json:"highlightStr"`
			} `json:"bestShowSinger"`
			BestShowAlbum interface{} `json:"bestShowAlbum"`
			BestShowMv    interface{} `json:"bestShowMv"`
		} `json:"bestShow"`
		SongResult    interface{} `json:"songResult"`
		TagSongResult interface{} `json:"tagSongResult"`
		SongsData     struct {
			Total int `json:"total"`
			Items []struct {
				Id          string `json:"id"`
				Name        string `json:"name"`
				CopyrightId string `json:"copyrightId"`
				Singers     []struct {
					Id    string      `json:"id"`
					Name  string      `json:"name"`
					Image interface{} `json:"image"`
				} `json:"singers"`
				Album struct {
					Id   string `json:"id"`
					Name string `json:"name"`
					Type int    `json:"type"`
				} `json:"album"`
				Mv *struct {
					CopyrightId string `json:"copyrightId"`
					ProductId   string `json:"productId"`
				} `json:"mv"`
				Crbt *struct {
					Name            string      `json:"name"`
					CopyrightId     string      `json:"copyrightId"`
					ProductId       string      `json:"productId"`
					Type            string      `json:"type"`
					Price           string      `json:"price"`
					VipFlag         int         `json:"vipFlag"`
					VipDownload     int         `json:"vipDownload"`
					AuditionsType   interface{} `json:"auditionsType"`
					AuditionsLength interface{} `json:"auditionsLength"`
					FirstPublish    int         `json:"firstPublish"`
					AllowDownload   int         `json:"allowDownload"`
					ToneType        string      `json:"toneType"`
					AuditionsFlag   int         `json:"auditionsFlag"`
					AccuracyLevel   int         `json:"accuracyLevel"`
					SpecialArea     interface{} `json:"specialArea"`
					CopyrightScope  interface{} `json:"copyrightScope"`
					LibraryType     interface{} `json:"libraryType"`
					Audio3D         int         `json:"audio3D"`
					ConcertId       interface{} `json:"concertId"`
					VrbtPublic      int         `json:"vrbtPublic"`
					Province        interface{} `json:"province"`
					NineSeconds     int         `json:"nineSeconds"`
					ProductLength   interface{} `json:"productLength"`
					AspectRatio     interface{} `json:"aspectRatio"`
					FormatId        string      `json:"formatId"`
				} `json:"crbt"`
				Ring struct {
					Name            string      `json:"name"`
					CopyrightId     string      `json:"copyrightId"`
					ProductId       string      `json:"productId"`
					Type            string      `json:"type"`
					Price           string      `json:"price"`
					VipFlag         int         `json:"vipFlag"`
					VipDownload     int         `json:"vipDownload"`
					AuditionsType   interface{} `json:"auditionsType"`
					AuditionsLength interface{} `json:"auditionsLength"`
					FirstPublish    int         `json:"firstPublish"`
					AllowDownload   int         `json:"allowDownload"`
					ToneType        interface{} `json:"toneType"`
					AuditionsFlag   int         `json:"auditionsFlag"`
					AccuracyLevel   int         `json:"accuracyLevel"`
					SpecialArea     interface{} `json:"specialArea"`
					CopyrightScope  interface{} `json:"copyrightScope"`
					LibraryType     interface{} `json:"libraryType"`
					Audio3D         int         `json:"audio3D"`
					ConcertId       interface{} `json:"concertId"`
					VrbtPublic      int         `json:"vrbtPublic"`
					Province        interface{} `json:"province"`
					NineSeconds     int         `json:"nineSeconds"`
					ProductLength   *string     `json:"productLength"`
					AspectRatio     interface{} `json:"aspectRatio"`
					FormatId        string      `json:"formatId"`
				} `json:"ring"`
				FullSong struct {
					Name            string      `json:"name"`
					CopyrightId     string      `json:"copyrightId"`
					ProductId       string      `json:"productId"`
					Type            string      `json:"type"`
					Price           string      `json:"price"`
					VipFlag         int         `json:"vipFlag"`
					VipDownload     int         `json:"vipDownload"`
					AuditionsType   *string     `json:"auditionsType"`
					AuditionsLength *string     `json:"auditionsLength"`
					FirstPublish    int         `json:"firstPublish"`
					AllowDownload   int         `json:"allowDownload"`
					ToneType        interface{} `json:"toneType"`
					AuditionsFlag   int         `json:"auditionsFlag"`
					AccuracyLevel   int         `json:"accuracyLevel"`
					SpecialArea     interface{} `json:"specialArea"`
					CopyrightScope  interface{} `json:"copyrightScope"`
					LibraryType     interface{} `json:"libraryType"`
					Audio3D         int         `json:"audio3D"`
					ConcertId       interface{} `json:"concertId"`
					VrbtPublic      int         `json:"vrbtPublic"`
					Province        interface{} `json:"province"`
					NineSeconds     int         `json:"nineSeconds"`
					ProductLength   interface{} `json:"productLength"`
					AspectRatio     interface{} `json:"aspectRatio"`
					FormatId        string      `json:"formatId"`
				} `json:"fullSong"`
				WalkMan struct {
					Name            string      `json:"name"`
					CopyrightId     string      `json:"copyrightId"`
					ProductId       string      `json:"productId"`
					Type            string      `json:"type"`
					Price           string      `json:"price"`
					VipFlag         int         `json:"vipFlag"`
					VipDownload     int         `json:"vipDownload"`
					AuditionsType   *string     `json:"auditionsType"`
					AuditionsLength *string     `json:"auditionsLength"`
					FirstPublish    int         `json:"firstPublish"`
					AllowDownload   int         `json:"allowDownload"`
					ToneType        interface{} `json:"toneType"`
					AuditionsFlag   int         `json:"auditionsFlag"`
					AccuracyLevel   int         `json:"accuracyLevel"`
					SpecialArea     interface{} `json:"specialArea"`
					CopyrightScope  interface{} `json:"copyrightScope"`
					LibraryType     interface{} `json:"libraryType"`
					Audio3D         int         `json:"audio3D"`
					ConcertId       interface{} `json:"concertId"`
					VrbtPublic      int         `json:"vrbtPublic"`
					Province        interface{} `json:"province"`
					NineSeconds     int         `json:"nineSeconds"`
					ProductLength   interface{} `json:"productLength"`
					AspectRatio     interface{} `json:"aspectRatio"`
					FormatId        string      `json:"formatId"`
				} `json:"walkMan"`
				Hq struct {
					Name            string      `json:"name"`
					CopyrightId     string      `json:"copyrightId"`
					ProductId       string      `json:"productId"`
					Type            string      `json:"type"`
					Price           string      `json:"price"`
					VipFlag         int         `json:"vipFlag"`
					VipDownload     int         `json:"vipDownload"`
					AuditionsType   *string     `json:"auditionsType"`
					AuditionsLength *string     `json:"auditionsLength"`
					FirstPublish    int         `json:"firstPublish"`
					AllowDownload   int         `json:"allowDownload"`
					ToneType        interface{} `json:"toneType"`
					AuditionsFlag   int         `json:"auditionsFlag"`
					AccuracyLevel   int         `json:"accuracyLevel"`
					SpecialArea     interface{} `json:"specialArea"`
					CopyrightScope  interface{} `json:"copyrightScope"`
					LibraryType     interface{} `json:"libraryType"`
					Audio3D         int         `json:"audio3D"`
					ConcertId       interface{} `json:"concertId"`
					VrbtPublic      int         `json:"vrbtPublic"`
					Province        interface{} `json:"province"`
					NineSeconds     int         `json:"nineSeconds"`
					ProductLength   interface{} `json:"productLength"`
					AspectRatio     interface{} `json:"aspectRatio"`
					FormatId        string      `json:"formatId"`
				} `json:"hq"`
				Sq struct {
					Name            string      `json:"name"`
					CopyrightId     string      `json:"copyrightId"`
					ProductId       string      `json:"productId"`
					Type            string      `json:"type"`
					Price           string      `json:"price"`
					VipFlag         int         `json:"vipFlag"`
					VipDownload     int         `json:"vipDownload"`
					AuditionsType   *string     `json:"auditionsType"`
					AuditionsLength *string     `json:"auditionsLength"`
					FirstPublish    int         `json:"firstPublish"`
					AllowDownload   int         `json:"allowDownload"`
					ToneType        interface{} `json:"toneType"`
					AuditionsFlag   int         `json:"auditionsFlag"`
					AccuracyLevel   int         `json:"accuracyLevel"`
					SpecialArea     interface{} `json:"specialArea"`
					CopyrightScope  interface{} `json:"copyrightScope"`
					LibraryType     interface{} `json:"libraryType"`
					Audio3D         int         `json:"audio3D"`
					ConcertId       interface{} `json:"concertId"`
					VrbtPublic      int         `json:"vrbtPublic"`
					Province        interface{} `json:"province"`
					NineSeconds     int         `json:"nineSeconds"`
					ProductLength   interface{} `json:"productLength"`
					AspectRatio     interface{} `json:"aspectRatio"`
					FormatId        string      `json:"formatId"`
				} `json:"sq"`
				Bit24 *struct {
					Name            string      `json:"name"`
					CopyrightId     string      `json:"copyrightId"`
					ProductId       string      `json:"productId"`
					Type            string      `json:"type"`
					Price           string      `json:"price"`
					VipFlag         int         `json:"vipFlag"`
					VipDownload     int         `json:"vipDownload"`
					AuditionsType   *string     `json:"auditionsType"`
					AuditionsLength *string     `json:"auditionsLength"`
					FirstPublish    int         `json:"firstPublish"`
					AllowDownload   int         `json:"allowDownload"`
					ToneType        interface{} `json:"toneType"`
					AuditionsFlag   int         `json:"auditionsFlag"`
					AccuracyLevel   int         `json:"accuracyLevel"`
					SpecialArea     interface{} `json:"specialArea"`
					CopyrightScope  interface{} `json:"copyrightScope"`
					LibraryType     interface{} `json:"libraryType"`
					Audio3D         int         `json:"audio3D"`
					ConcertId       interface{} `json:"concertId"`
					VrbtPublic      int         `json:"vrbtPublic"`
					Province        interface{} `json:"province"`
					NineSeconds     int         `json:"nineSeconds"`
					ProductLength   interface{} `json:"productLength"`
					AspectRatio     interface{} `json:"aspectRatio"`
					FormatId        string      `json:"formatId"`
				} `json:"bit24"`
				D3 *struct {
					Name            string      `json:"name"`
					CopyrightId     string      `json:"copyrightId"`
					ProductId       string      `json:"productId"`
					Type            string      `json:"type"`
					Price           string      `json:"price"`
					VipFlag         int         `json:"vipFlag"`
					VipDownload     int         `json:"vipDownload"`
					AuditionsType   string      `json:"auditionsType"`
					AuditionsLength string      `json:"auditionsLength"`
					FirstPublish    int         `json:"firstPublish"`
					AllowDownload   int         `json:"allowDownload"`
					ToneType        interface{} `json:"toneType"`
					AuditionsFlag   int         `json:"auditionsFlag"`
					AccuracyLevel   int         `json:"accuracyLevel"`
					SpecialArea     interface{} `json:"specialArea"`
					CopyrightScope  interface{} `json:"copyrightScope"`
					LibraryType     interface{} `json:"libraryType"`
					Audio3D         int         `json:"audio3D"`
					ConcertId       interface{} `json:"concertId"`
					VrbtPublic      int         `json:"vrbtPublic"`
					Province        interface{} `json:"province"`
					NineSeconds     int         `json:"nineSeconds"`
					ProductLength   interface{} `json:"productLength"`
					AspectRatio     interface{} `json:"aspectRatio"`
					FormatId        string      `json:"formatId"`
				} `json:"d3"`
				SmallPic     string      `json:"smallPic"`
				MediumPic    string      `json:"mediumPic"`
				LargePic     string      `json:"largePic"`
				Lyric        interface{} `json:"lyric"`
				HighlightStr []string    `json:"highlightStr"`
			} `json:"items"`
		} `json:"songsData"`
		TagPriority int `json:"tagPriority"`
		Total       int `json:"total"`
	} `json:"data"`
}
